spring:
  datasource:
    url: jdbc:mysql://work-mysql:3306/work_collaborative_images
    druid:
        allow:
  redis:
    database: 1 # Redis 数据库索引(默认为 0, 通常为了方便开发会认为 0 号为生产环境、1 号为测试环境、2 号为开发环境)
    host: work-redis # Redis 服务器地址
  cloud:
    sentinel:
      transport:
        port: 8721
        dashboard: work-sentinel:8131 # 不过在容器模式下是无法访问宿主的, 因此开发模式下控制台失效, 但是不代表无法注册到控制台, 并且流量治理功能还是可用
  elasticsearch:
    uris: http://work-elasticsearch:9200
server:
  address: 0.0.0.0
nacos:
  config:
    server-addr: work-nacos:8848 # nacos 地址
